from typing import Protocol
from app.engine.types import Node, Edge, Signal


class GraphRepo(Protocol):
    def get_nodes(self) -> list[Node]: ...
    def get_edges(self) -> list[Edge]: ...
    def get_node(self, node_id: str) -> Node | None: ...


class SignalRepo(Protocol):
    def list(self, since: float | None = None) -> list[Signal]: ...
    def add(self, sig: Signal) -> None: ...


class IncidentRepo(Protocol):
    def get(self, incident_id: str) -> dict | None: ...
    def list_all(self) -> list[dict]: ...
    def update(self, incident_id: str, data: dict) -> None: ...


class RootCauseRepo(Protocol):
    def get(self, incident_id: str) -> dict | None: ...
    def save(self, incident_id: str, data: dict) -> None: ...


class InterventionRepo(Protocol):
    def list_for_incident(self, incident_id: str) -> list[dict]: ...
    def get_library(self) -> list[dict]: ...


class SimulationRepo(Protocol):
    def get(self, sim_id: str) -> dict | None: ...
    def save(self, sim_id: str, data: dict) -> None: ...
    def list_for_incident(self, incident_id: str) -> list[dict]: ...


class DecisionRepo(Protocol):
    def get(self, decision_id: str) -> dict | None: ...
    def save(self, decision_id: str, data: dict) -> None: ...
    def list_for_incident(self, incident_id: str) -> list[dict]: ...


class WizardRepo(Protocol):
    def get(self, incident_id: str) -> dict | None: ...
    def save(self, incident_id: str, data: dict) -> None: ...


class SourceRepo(Protocol):
    def get(self, source_id: str) -> dict | None: ...
    def list_all(self) -> list[dict]: ...
    def save(self, source_id: str, data: dict) -> None: ...
    def delete(self, source_id: str) -> None: ...


class RepoBundle(Protocol):
    graph: GraphRepo
    signals: SignalRepo
    incidents: IncidentRepo
    root_causes: RootCauseRepo
    interventions: InterventionRepo
    simulations: SimulationRepo
    decisions: DecisionRepo
    wizard: WizardRepo
    sources: SourceRepo
