// AUTO: Arabic->English labels (build-time translation). 162 entries.
export const LABELS: Record<string,string> = {
 "Amman Bus": "Amman Bus",
 "Bekhedmetkom": "Bekhedmetkom (At Your Service)",
 "FinancialAid": "Financial aid",
 "National Aid Fund": "National Aid Fund",
 "National Aid Fund Delays": "National Aid Fund payment delays",
 "NationalAidFund": "National Aid Fund",
 "Sanad": "Sanad",
 "TakafelPlatform": "Takaful Platform",
 "Takaful": "Takaful",
 "Takaful Platform": "Takaful Platform",
 "Takaful platform": "Takaful Platform",
 "TakafulPlatform": "Takaful Platform",
 "Takaful_Platform": "Takaful Platform",
 "Takaful_platform": "Takaful Platform",
 "corruption": "Corruption",
 "digital_services": "Digital Services",
 "education": "Education",
 "electricity": "Electricity",
 "financial_aid": "Financial Aid",
 "general": "General",
 "general_service": "General Service",
 "healthcare": "Healthcare",
 "housing": "Housing",
 "national Aid Fund": "National Aid Fund",
 "national_aid": "National Aid Fund",
 "national_aid_fund": "National Aid Fund",
 "nationalaidfund": "National Aid Fund",
 "public_safety": "Public Safety",
 "roads": "Roads",
 "takafel_platform": "Takaful Platform",
 "takafol-platform": "Takaful Platform",
 "takafol_platform": "Takaful Platform",
 "takafol_platform_issue": "Takaful Platform Issue",
 "takaful": "Takaful",
 "takaful_national_aid": "Takaful National Aid",
 "takaful_platform": "Takaful Platform",
 "takaful_platform_issue": "Takaful platform issue",
 "test": "Test",
 "traffic": "Traffic",
 "water": "Water",
 "إدارة_الامتحانات": "Exams Administration",
 "إصلاح الطريق": "Road repair",
 "إصلاح شبكة الصرف الصحي": "Sewage network repair",
 "إنارة الشوارع": "Street lighting",
 "اجبار_المسار_الاكاديمي": "Forced academic track assignment",
 "استئجار_سيارات_الضمان": "Social Security car rentals",
 "استبدال_15_ألف_مدفأة": "Replacing 15,000 heaters",
 "استخراج الهوية الوطنية": "National ID issuance",
 "استخراج وثيقة ميلاد": "Issue birth certificate",
 "اصول_نقابة_المعلمين": "Teachers Syndicate assets",
 "اعفاء_فواتير_المستفيدين": "Beneficiary bill exemption",
 "اعلان_الخلل_الفني": "Technical malfunction notice",
 "اعلان_صرف_رسمي": "Official disbursement announcement",
 "اقتطاعات_نقابة_المعلمين": "Teachers Syndicate deductions",
 "الأثر_الرجعي_مواليد_2009": "Retroactive effect for those born in 2009",
 "الاستراتيجية_الوطنية_للحماية_الاجتماعية": "National Social Protection Strategy",
 "البيئة_المدرسية": "School environment",
 "التعليم_المهني": "Vocational education",
 "التعيينات_بالوزارة": "Ministry appointments",
 "التقاعد_المبكر_360_اشتراك": "Early retirement with 360 contributions",
 "التمكين_الاقتصادي": "Economic Empowerment",
 "الثقة_بالبرلمان": "Trust in Parliament",
 "الخدمات_الإلكترونية": "Electronic Services",
 "الدبلوم_العالي_اعداد_المعلمين": "Higher Diploma in Teacher Preparation",
 "الدعم_الاجتماعي_للأسر_الفقيرة": "Social Support for Poor Families",
 "الدوام_المدرسي_الصيفي": "Summer School Hours",
 "الدوام_المسائي": "Evening Shift",
 "الضغط_النفسي_الطلاب": "Student Psychological Stress",
 "الضمان_الاجتماعي_المخالفات_المالية": "Social Security Financial Violations",
 "العنف_المدرسي": "School Violence",
 "المجلس_الاقتصادي_والاجتماعي": "Economic and Social Council",
 "المكرمة_الملكية": "Royal Grant (Al-Makruma)",
 "المكرمة_الملكية_60_ألف_أسرة": "Royal Grant – 60,000 Families",
 "المكرمة_الملكية_صندوق_المعونة": "Royal Grant – National Aid Fund",
 "المناهج_الدراسية": "School Curricula",
 "المناهج_الصف_الأول": "First Grade Curriculum",
 "اولويات_الحكومة": "Government Priorities",
 "بدل_التنقل_موظفي_الضمان": "Transport Allowance for Social Security Staff",
 "تأخير_صرف_العيد": "Delayed Eid bonus payment",
 "تجديد جواز السفر": "Passport renewal",
 "تحييد_التعليم_سياسيا": "Keep education out of politics",
 "تخصصات_غير_مطلوبة": "Unneeded academic majors",
 "ترخيص تجاري": "Commercial license",
 "تسجيل عقار": "Property registration",
 "تصريح بناء": "Building Permit",
 "تصريح عمل": "Work Permit",
 "تطبيق_المحفظة_الالكترونية": "E-Wallet App",
 "تعديل_قانون_الضمان_2026": "2026 Social Security Law Amendment",
 "تعيينات_2026_تعليم": "2026 Teaching Appointments",
 "تكافل": "Takaful (Solidarity Aid Program)",
 "تكرار_الخلل_الفني": "Recurring technical malfunction",
 "تكلفة_الدبلوم_العالي": "Higher diploma cost",
 "تمييز_ضد_المعلمين_الذكور": "Discrimination against male teachers",
 "توزيع_الوظائف_الجغرافي": "Geographic distribution of jobs",
 "توزيع_طلاب_الصف_11": "Grade 11 student distribution",
 "توصيل شبكة المياه": "Water network connection",
 "توظيف_6_شواغر": "Hiring: 6 vacancies",
 "توفير دواء مزمن": "Provide chronic-illness medication",
 "جوازات_السفر": "Passports",
 "حذف_استراحة_5_دقايق": "Remove the 5-minute break",
 "حصص_الإناث_بالتوظيف": "Female hiring quotas",
 "خدمات_البطاقة_الذكية": "Smart card services",
 "خطة_توظيف_2027_اناث": "2027 Employment Plan (Female)",
 "دعم أسري": "Family Support",
 "ديون_الاسر_الفقيرة": "Poor Families' Debts",
 "رابط_التقديم": "Application Link",
 "رابط_التقديم_وزارة_التربية": "Application Link - Ministry of Education",
 "رخصة قيادة": "Driver's License",
 "رواتب_المعلمين": "Teachers' salaries",
 "رواتب_المعونة": "Welfare aid salaries",
 "رواتب_لا_تكفي": "Salaries too low to live on",
 "زيادة_اشتراكات_الضمان": "Social security contribution increase",
 "سحب_اشتراكات_الضمان": "Withdrawing social security contributions",
 "سلامة_المدافئ": "Heater safety",
 "سياسة_التمكين_الاقتصادي": "Economic Empowerment Policy",
 "شؤون_المعلمين": "Teachers' Affairs",
 "شرط_الاقامة_بالمحافظة": "Governorate residency requirement",
 "شركة_توزيع_المعونة": "Aid distribution company",
 "شروط_المكرمة_الملكية": "Royal Grant eligibility conditions",
 "شروط_خبرة_المعلمين": "Teacher experience requirements",
 "شواغر_المعلمين_قصبة_اربد": "Teacher vacancies, Qasabat Irbid",
 "شواغر_برنامج_الحقول": "Field Program vacancies",
 "صرف راتب التقاعد": "Pension payment disbursement",
 "صرف_المعونات_الشهرية": "Monthly aid disbursement",
 "صرف_المعونات_نوفمبر": "November aid disbursement",
 "صرف_مستحقات_قبل_العيد": "Pre-Eid dues disbursement",
 "صندوق_المعونة_المحافظ_الالكترونية": "Aid Fund - Electronic Wallets",
 "صندوق_المعونة_بطاقات_100_دينار": "Aid Fund - 100 Dinar Cards",
 "صيانة مدرسة": "School maintenance",
 "طرق_وبنية_تحتية": "Roads and infrastructure",
 "طلب إعفاء ضريبي": "Tax exemption request",
 "علاج في المستشفى الحكومي": "Treatment at public hospital",
 "عمولة_المحافظ_الالكترونية": "E-wallet fees",
 "قانون_الضمان_الاجتماعي_2026": "Social Security Law 2026",
 "قنوات_الشكاوى": "Complaint channels",
 "قيمة_المكرمة_الملكية": "Royal grant amount",
 "محاسبة_الفاسدين_الضمان": "Holding Social Security corrupt officials accountable",
 "مراكز_الخدمة": "Service centers",
 "مراكز_ذوي_الإعاقة": "Disability Centers",
 "مساعدة اجتماعية": "Social Assistance",
 "مشكلة_المحافظ_الالكترونية": "E-wallet problem",
 "معايير_الاستحقاق": "Eligibility Criteria",
 "معدات_مراكز_الاعاقة": "Disability center equipment",
 "معيل_الاسرة": "Family Breadwinner",
 "نتائج_التوجيهي_2026": "Tawjihi Results 2026",
 "نسبة_نجاح_اقتصاد_منزلي": "Home Economics Stream Pass Rate",
 "نسبة_نجاح_الشرعي": "Sharia Stream Pass Rate",
 "نسبة_نجاح_الصناعي": "Industrial Stream Pass Rate",
 "نظام_التعليم": "Education System",
 "نقابة_المعلمين": "Teachers Syndicate",
 "نقص_المعونة_الخلل_الفني": "Aid shortage - technical error",
 "نقل سجل قيد": "Civil registry record transfer",
 "نقل_عام": "Public transportation",
 "وزن_الحقيبة_المدرسية": "School bag weight",
 "Complaint": "Complaint",
 "access_issue": "Access issue",
 "aid_criteria": "Aid eligibility criteria",
 "allowance_violation": "Allowance violation",
 "amount_insufficient": "Amount insufficient",
 "app_problem": "App problem",
 "app_review": "App review",
 "application_link_request": "Application link request"
}
export const t = (s?: string|null) => (s && LABELS[s]) ? LABELS[s] : (s ?? '')